name: ml-ids-api
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - awscli=1.16.297
  - boto3=1.10.30
  - gevent=1.4.0
  - flask=1.1.1
  - gunicorn=20.0.4
  - mypy=0.750
  - numpy=1.17.2
  - pandas=0.25.2
  - pylint=2.4.4
  - pip=19.2.3
  - pytest=5.2.1
  - pytest-runner=5.1
  - python=3.7.3
  - requests=2.22.0
  - responses=0.10.6
  - setuptools=41.6.0
  - pip:
