class TestConfig(object):
    AWS_REGION = 'AWS_REGION'
    AWS_ACCESS_KEY = 'AWS_ACCESS_KEY'
    AWS_SECRET_KEY = 'AWS_SECRET_KEY'
    AWS_SAGEMAKER_HOST = 'AWS_SAGEMAKER_HOST'
    AWS_SAGEMAKER_ENDPOINT = 'AWS_SAGEMAKER_ENDPOINT'
    AWS_SNS_PREDICTIONS_TOPIC = 'AWS_SNS_PREDICTIONS_TOPIC'
